### ISSUE TITLE
Fails to connect to ES 7.12.0 with ssl 

### ISSUE THREAD

**Issue by robomotic** [avlahop/dask-elk#29]
Hi folks,
I am on Python 3.7 with ES 7.12.0 with ssl enabled (self signed).

Not sure if is related to the other issue but I am trying to replicate my python ES setup in dask-elk like so:

`client = DaskElasticClient(host=cfg['host'],port=cfg['port'],password=cfg['passwd'],scheme="https",client_kwargs={'verify_certs':False,'ssl_show_warn':False},warn_only=True)`

Query:

```
query = {
    "query" : {
        "term" : { "ciao.keyword" : "123" }
    }
}

df = client.read(query=query, index='day-2021-05-04', doc_type='_doc')

```

I am getting:

`SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)`

Everything works fine if I use the ES connector:

```
 es_url = "{0}://{1}:{2}@{3}:{4}".format(cfg['protocol'],cfg['user'],cfg['passwd'],cfg['host'],cfg['port'])
 es = Elasticsearch(es_url,verify_certs=False,ssl_show_warn=False)
```

**Comment by robomotic** [comment]
Ping??

**Comment by robomotic** [comment]
I can see why this is happening the parse kwargs is only filtering user and pass therefore ignoring the rest. I am going to create a patch or a fork where I can pass an es client object directly instead of brokering the args.

**Comment by priamai** [comment]
Actually my bad, this is the way it was supposed to work:

```
        client = DaskElasticClient(host=cfg['host'],port=cfg['port'],username=cfg['user'],
                                   password=cfg['passwd'],
                                   scheme="https",
                                   verify_certs=False,ssl_show_warn=False,
                                   warn_only=True)
```
works as expected now closing.

**Comment by Cognitus-Stuti** [comment]
@priamai did it actually work for you, could you please share your code?

**Comment by priamai** [comment]
Yes it was working but that is now 3 years ago man!
